name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: ticketing-dev
  GKE_ZONE: us-central1-c
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          USE_GKE_GCLOUD_AUTH_PLUGIN: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}
      - name: Configure Docker
        run: gcloud --quiet auth configure-docker
      - name: Get GKE Credentials
        run: |-
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Build Docker Image
        run: cd auth && docker build -t "us.gcr.io/$PROJECT_ID/auth" .
      - run: docker push "us.gcr.io/$PROJECT_ID/auth"
      - run: export USE_GKE_GCLOUD_AUTH_PLUGIN=true && kubectl rollout restart deployment auth-depl


