name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: ticketing-dev
  GKE_ZONE: us-central1-c
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          USE_GKE_GCLOUD_AUTH_PLUGIN: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - run: |-
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud components install gke-gcloud-auth-plugin
          kubectl apply -f infra/k8s 
          kubectl apply -f infra/k8s-prod

